### ISSUE TITLE
Subsequent variable names in list are not being highlighted

### ISSUE THREAD

**Issue by Gauntlet173** [smucclaw/ide#37]
<img width="759" alt="Screenshot 2021-03-26 at 1 01 39 PM" src="https://user-images.githubusercontent.com/11790846/112584789-7d347c00-8e33-11eb-9c51-e9d63551f8e1.png">

See ea in the for statement and other_practice in the exists statement.

**Comment by kharus** [comment]
@Gauntlet173 Can you please post this snippet as a text?

**Comment by kharus** [comment]
Or reference the file.

**Comment by Gauntlet173** [comment]
Right.

Baby-l4/L4/r34.l4 in the add r34.l4 branch

**Comment by kharus** [comment]
![image](https://user-images.githubusercontent.com/1381805/112920670-00a7e300-913c-11eb-9070-a49a5938cd01.png)

**Comment by kharus** [comment]
@Gauntlet173 Please try new version
